
data_dir : B:\keras_project_2\data\
path_images : B:\keras_project_2\data\101_ObjectCategories\airplanes\
path_annot : B:\keras_project_2\data\Annotations\Airplanes_Side_2\


csv_dir : .\logs\csv_logs
csv_file : airplanes_side_2.csv
check_dir : .\logs\checkpoint\
check_file : airplanes_side_2.h5

image_size : 224 

input_shape :
  - 224
  - 224
  - 3
patch_size :  32 
projection_dim : 64
num_heads : 4
transformer_units: 
  - 128
  - 64

transformer_layers: 4
learning_rate : 0.001
weight_decay : 0.0001
mlp_head_units :
  - 2048
  - 1024 
  - 512 
  - 64 
  - 32

batch_size : 32
num_epochs : 100
history : []
transformer_units : 
  - 64
  - 64


...