path_images : "/101_ObjectCategories/airplanes/"
path_annot : "/Annotations/Airplanes_Side_2/"
image_size : 224 

input_shape :
  - 3
  - 224
  - 224
patch_size :
num_patches :
projection_dim :
num_heads :
transformer_units:
transformer_layersmlp_head_units :

